ALTER TABLE users ADD COLUMN IF NOT EXISTS fcm_token TEXT;
ALTER TABLE morning_messages
    ADD COLUMN IF NOT EXISTS prompt_tokens     INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS completion_tokens INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS latency_ms        INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS model             TEXT NOT NULL DEFAULT '';
