#!/bin/bash
# One-time provisioning of a fresh Ubuntu 22.04/24.04 VPS for the Companion backend.
# Run as root ON THE SERVER:  bash setup.sh api.companion.keegooroomie.ru
#
# What it does: Postgres (with a generated password), Caddy (auto TLS), app user and dirs,
# firewall, /opt/companion/.env with DATABASE_URL filled in. Safe to re-run: existing
# .env and DB user are kept.
set -euo pipefail

DOMAIN="${1:?Usage: $0 DOMAIN   (e.g. api.companion.keegooroomie.ru)}"
APP_USER="companion"
APP_DIR="/opt/companion"
ENV_FILE="$APP_DIR/.env"

echo "==> Installing system packages"
apt-get update -q
apt-get install -y -q postgresql postgresql-contrib curl ufw openssl \
    debian-keyring debian-archive-keyring apt-transport-https gnupg

echo "==> Installing Caddy"
if ! command -v caddy >/dev/null; then
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -q
    apt-get install -y -q caddy
fi

echo "==> Server time zone → Europe/Moscow (logs and cron read naturally)"
timedatectl set-timezone Europe/Moscow || true

echo "==> Creating app user and directories"
id -u "$APP_USER" &>/dev/null || useradd --system --shell /usr/sbin/nologin --home "$APP_DIR" "$APP_USER"
mkdir -p "$APP_DIR/migrations" /var/log/companion /var/log/caddy /var/backups/companion
chown "$APP_USER:$APP_USER" "$APP_DIR" /var/log/companion

echo "==> Configuring PostgreSQL"
systemctl enable --now postgresql
if [ ! -f "$ENV_FILE" ]; then
    DB_PASS="$(openssl rand -hex 24)"
    if sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='companion'" | grep -q 1; then
        sudo -u postgres psql -qc "ALTER USER companion WITH PASSWORD '$DB_PASS';"
    else
        sudo -u postgres psql -qc "CREATE USER companion WITH PASSWORD '$DB_PASS';"
    fi
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='companion'" | grep -q 1 \
        || sudo -u postgres psql -qc "CREATE DATABASE companion OWNER companion;"

    echo "==> Writing $ENV_FILE (fill in LLM_API_KEY and DEV_USER_IDS)"
    cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -I). Never commit this file.
DATABASE_URL=postgres://companion:${DB_PASS}@localhost:5432/companion?sslmode=disable
PORT=8080
# API only on localhost — Caddy is the single way in
LISTEN_ADDR=127.0.0.1:8080
ENV=production
APP_TZ=Europe/Moscow

# Prompt admin (local-only port; use deploy/prompt.sh from your machine)
ADMIN_ADDR=127.0.0.1:9090
ADMIN_TOKEN=$(openssl rand -hex 32)
# Optional: announce prompt changes in Telegram
TG_BOT_TOKEN=
TG_CHAT_ID=

# cloud.ru Foundation Models (OpenAI-compatible)
LLM_API_KEY=
LLM_BASE_URL=https://api.cloud.ru/v1
LLM_MODEL=GigaChat-3-Pro
LLM_DAILY_CAP=300
LLM_PRICE_IN_PER_1M=73.03
LLM_PRICE_OUT_PER_1M=176.39

# Comma-separated user ids excluded from metrics (your own devices)
DEV_USER_IDS=
# Origin allowed to read /api/v1/metrics (the GitHub Pages site); * = anyone
METRICS_ALLOWED_ORIGIN=*
EOF
    chmod 600 "$ENV_FILE"
    chown "$APP_USER:$APP_USER" "$ENV_FILE"
else
    echo "    $ENV_FILE exists — keeping it and the DB password"
    # Add keys introduced later, without touching existing values
    grep -q '^LISTEN_ADDR=' "$ENV_FILE" || echo 'LISTEN_ADDR=127.0.0.1:8080' >> "$ENV_FILE"
    grep -q '^ADMIN_ADDR=' "$ENV_FILE"  || echo 'ADMIN_ADDR=127.0.0.1:9090' >> "$ENV_FILE"
    grep -q '^ADMIN_TOKEN=' "$ENV_FILE" || echo "ADMIN_TOKEN=$(openssl rand -hex 32)" >> "$ENV_FILE"
fi

echo "==> Configuring firewall"
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable

echo "==> Writing Caddyfile for $DOMAIN"
cat > /etc/caddy/Caddyfile <<EOF
${DOMAIN} {
	reverse_proxy localhost:8080
	encode gzip

	header {
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
		Referrer-Policy strict-origin-when-cross-origin
		-Server
	}

	log {
		output file /var/log/caddy/companion.log {
			roll_size 10mb
			roll_keep 5
		}
		format json
	}
}
EOF
caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
systemctl reload caddy || systemctl restart caddy

echo "==> Nightly DB backup (03:30, keep 7 days)"
cat > /etc/cron.d/companion-backup <<'EOF'
30 3 * * * postgres pg_dump -Fc companion > /var/backups/companion/companion-$(date +\%F).dump && find /var/backups/companion -name '*.dump' -mtime +7 -delete
EOF
chown postgres:postgres /var/backups/companion

echo ""
echo "==> Done. Next, from your machine:"
echo "    1. Put LLM_API_KEY into $ENV_FILE on the server"
echo "    2. bash deploy/deploy.sh <server-ip-or-host>"
